### ISSUE TITLE
[contribution] Add icons

### ISSUE THREAD

**Issue by angelhdzmultimedia** [miguelsolorio/vscode-symbols#183]
### Hello!
Congratulations for this very nice extension and icons design. 🔥👏 it's my favorite so far.

I want to contribute with some icons, followed the contribution guide and used colors from the existing icons (Pinia stores one was a bit demanding).

![image](https://github.com/miguelsolorio/vscode-symbols/assets/10191085/c67b0684-eacd-4a92-b6c1-61b847fcb565)

Please provide tips on what to improve, before actually submitting a pr. Thanks.

**Comment by angelhdzmultimedia** [comment]
### New

![image](https://github.com/miguelsolorio/vscode-symbols/assets/10191085/350dd685-9899-4a00-83e5-2e2fdbf7ef16)

**Comment by angelhdzmultimedia** [comment]
![image](https://github.com/miguelsolorio/vscode-symbols/assets/10191085/844ad928-43e1-4ccc-af70-fe0fff2330e4)

**Comment by miguelsolorio** [comment]
@angelhdzmultimedia thanks for your interest in contributing to the project! I think what would be best if to create a PR for these changes so that I can inspect the icons more closely. I do have some guidelines I am following to keep the icons consistent (need to publish these).

I'm a little hesitant about the Nest + Quasar + Pinia (the folder color change) since those appear to be visually heavy. I think with some minor tweaks this can get better but just wanted to let you know. Feel free to create a PR and we can get started!

**Comment by miguelsolorio** [comment]
I'll go ahead and close this issue since you've added in your PRs. Thanks again!
