### ISSUE TITLE
Add Redux Icons and Folders 

### ISSUE THREAD

**Issue by keidsondesigner** [miguelsolorio/vscode-symbols#190]
It would be great to have a specific icon for Redux files and folders
- I've created some examples of the standard icons and folders

![Screenshot 2024-03-17 130341](https://github.com/miguelsolorio/vscode-symbols/assets/76180887/38c7b30d-00c9-45ef-9229-326116df4efa)

**Comment by miguelsolorio** [comment]
@keidsondesigner Thank you for using the template file! Can you share your Figma file so I can add them to the main one?

**Comment by keidsondesigner** [comment]
yep! what's your email?

**Comment by miguelsolorio** [comment]
You can just share a link that's visible to the public and I'll copy/paste them over

**Comment by keidsondesigner** [comment]
@miguelsolorio 

https://www.figma.com/file/UQQzTjcRvWsZW9udePXOSr/Symbols---File-Icons-(Copy)?type=design&mode=design&t=zIiTKZHz8wKOQz7H-0

**Comment by miguelsolorio** [comment]
Can you share what file names/patterns these map to?

**Comment by miguelsolorio** [comment]
@keidsondesigner I've been looking at other file icon themes and I can't find examples of file names that these would map to, do you mind providing some examples? I don't use redux/react so I wouldn't know.

**Comment by keidsondesigner** [comment]
Hi @miguelsolorio it looks like this
![Screenshot 2024-03-23 225947](https://github.com/miguelsolorio/vscode-symbols/assets/76180887/7ca2eab5-e14d-4e2c-9a14-ccc696e6fb46)
![Screenshot 2024-03-23 230202](https://github.com/miguelsolorio/vscode-symbols/assets/76180887/8f3c6158-a580-44a3-b970-678c36c2315f)

**Comment by miguelsolorio** [comment]
I've added these redux files:

![CleanShot 2024-03-27 at 11 21 08@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/cb6305bf-f194-4b3d-b307-139a22c69884)

I also added the related folder icons as well but did not assign them in the theme because the names are a little too generic to conflict with other folders names (actions, selector, etc.). I also noticed other file themes do a similar thing. Feel free to [define them in your user settings](https://github.com/miguelsolorio/vscode-symbols?tab=readme-ov-file#configuration) if you'd like to use them:

```json
  "symbols.folders.associations": {
    "actions": "folder-redux-actions",
    "facade": "folder-redux-facade",
    "reducer": "folder-redux-reducer",
    "selector": "folder-redux-selector",
    "effects": "folder-redux-effects"
  }
```

![CleanShot 2024-03-27 at 11 31 09@2x](https://github.com/miguelsolorio/vscode-symbols/assets/35271042/876c80e0-5199-43cc-97cf-5083fa987331)
